namespace StudyMate.Wpf.Models.Ai
{
    /// <summary>
    /// Represents a multiple-choice quiz question generated by the AI service.
    /// Contains the question text, four answer options, the correct answer index, and an explanation.
    /// </summary>
    public class QuizQuestion
    {
        /// <summary>
        /// Gets or sets the question text. Always in English regardless of source document language.
        /// </summary>
        public string Question { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the list of exactly four answer options. All options are in English.
        /// </summary>
        public List<string> Options { get; set; } = new List<string>();

        /// <summary>
        /// Gets or sets the zero-based index of the correct answer option (0-3).
        /// </summary>
        public int CorrectOptionIndex { get; set; }

        /// <summary>
        /// Gets or sets the explanation of why the correct answer is correct. Always in English.
        /// </summary>
        public string Explanation { get; set; } = string.Empty;
    }
}
